### ISSUE TITLE
Remove m.hotmail.com

### ISSUE THREAD

**Issue by An-dz** [FadeMind/hosts.extras#1]
I'm requesting to remove m.hotmail.com from Telemetry/hosts, the reason is explained here:
https://github.com/StevenBlack/hosts/issues/193

**Comment by FadeMind** [comment]
Telemetry was purged. 
See https://github.com/StevenBlack/hosts/tree/master/data/WindowsSpyBlocker

**Comment by An-dz** [comment]
Fine, but I'm on Linux. And my client can't fetch new emails from the live mail.

Have you checked if that connection occurs when you use a local account? Because if I'm not wrong on Win10 your emails will be synchronised automatically if you use a MS account.

**Comment by FadeMind** [comment]
Simpy add `m.hotmail.com` and other reqired domain to `whitelist` file and regenerate hosts file.
