### ISSUE TITLE
HideMyAss is a VPN provider

### ISSUE THREAD

**Issue by StevenBlack** [FadeMind/hosts.extras#11]
Hi @FadeMind Tomasz, happy new year!

HideMyAss (HMA) is a legitimate VPN provider, as far as I know.  The `add.Risk` hosts file has the following lines for it.

    0.0.0.0 1.hidemyass.com
    0.0.0.0 2.hidemyass.com
    0.0.0.0 3.hidemyass.com
    0.0.0.0 4.hidemyass.com
    0.0.0.0 5.hidemyass.com
    0.0.0.0 6.hidemyass.com
    0.0.0.0 7.hidemyass.com
    0.0.0.0 hidemyass.com
    0.0.0.0 www.hidemyass.com

I'm OK, either way.  I'm just wondering if you know something I don't about HMA.

**Comment by FadeMind** [comment]
@StevenBlack  Sorry for delayed response. I can whitelist these domains if needed. I don't know HMA at all.

**Comment by StevenBlack** [comment]
Thank you @FadeMind Tomasz!

**Comment by IDKwhattoputhere** [comment]
HMA is still in the hosts file at https://github.com/StevenBlack/hosts. Sorry if I'm missing something here.

**Comment by FadeMind** [comment]
You can always whitelist any domain.
