### ISSUE TITLE
False Positive report on our domain ip2location.com in your list

### ISSUE THREAD

**Issue by ip2location** [FadeMind/hosts.extras#15]
Hi FadeMind, recently when we viewed your host block lists, we noticed that our domain tools.ip2location.com was listed in hpHostsand hpHosts-ATS hosts file. It is wrong because the IP2Location is a geolocation look up database that can be used to reverse translate IP address to the geolocation information such as country and city. We have contacted the source to remove our domain from their list, and now we would like you to update your list to remove our domain from your list. Thank You.

**Comment by FadeMind** [comment]
@ip2location done. Regards
