### ISSUE TITLE
https://github.com/FadeMind/hosts.extras/issues

### ISSUE THREAD

**Issue by jbradsha** [FadeMind/hosts.extras#16]
Hi, I think you're the upstream for this... if not can you let me know? Thanks.
Citrix are a IT provider, their TLD is being blocked :-(

Match found in https://raw.githubusercontent.com/StevenBlack/hosts/master/data/UncheckyAds/hosts:
   www.citrix.com

**Comment by FadeMind** [comment]
Please report issue directly to: https://unchecky.com/contact
This is only copy of used by app hosts file.
Regards
