### ISSUE TITLE
False positive webtrack.dhlglobalmail.com

### ISSUE THREAD

**Issue by lightswitch05** [FadeMind/hosts.extras#21]
Hello, I believe `webtrack.dhlglobalmail.com` is a false positive. It shows shipping status tracking for deliveries for the DHL shipping company. I normally like to provide full URLs, but since it’s shipping, the only URL I have shows my home address

**Comment by FadeMind** [comment]
Where DIRECTLY it is stored?

**Comment by lightswitch05** [comment]
Its in https://raw.githubusercontent.com/FadeMind/hosts.extras/master/rlwpx.free.fr.htrc/hosts

Perhaps this isn't the right place for me to open a ticket?

**Comment by lightswitch05** [comment]
specifically line number 34726

**Comment by FadeMind** [comment]
@lightswitch05 done. Thanks for report.
