### ISSUE TITLE
Remove blacklisted website 

### ISSUE THREAD

**Issue by MarcoDiFrancesco** [FadeMind/hosts.extras#23]
Can you remove `it.altervista.org` from the blacklisted website? This is just the Italian website for `altervista.org` not a website of advertisements.
I've already asked to [Steven Black](https://github.com/StevenBlack/hosts/issues/917) to remove it and he sent me here.
Thanks

**Comment by FadeMind** [comment]
@MarcoDiFrancesco done. Thanks for report.
