### ISSUE TITLE
[Dead-Hosts] Result of execution 

### ISSUE THREAD

**Issue by funilrys** [FadeMind/hosts.extras#3]
Hello @FadeMind ,

As you (may) know, I released and still continue to develop [Funceble](https://github.com/funilrys/funceble).

I wanted to help, so you can find here the result of my last execution against the following list.

[hosts.extras--add.2o7Net@FadeMind](https://github.com/funilrys/dead-hosts/tree/master/hosts.extras--add.2o7Net%40FadeMind) ==> add.2o7Net  :white_check_mark: 

In between, 
Congratulations, :+1: :100: your [host list](https://github.com/FadeMind/hosts.extras/blob/master/add.2o7Net/hosts) don't have any dead domains.

Have a nice day/night.

Cheers,

**Comment by funilrys** [comment]
Hello @FadeMind ,

Just released the results for the following.

[hosts.extras--add.Dead@FadeMind](https://github.com/funilrys/dead-hosts/tree/master/hosts.extras--add.Dead%40FadeMind) ==> add.Dead :x:

Have a nice day/night.

Cheers,

**Comment by funilrys** [comment]
Hello @FadeMind ,

Just released the results for the following.

[hosts.extras--add.Risk@FadeMind](https://github.com/funilrys/dead-hosts/tree/master/hosts.extras--add.Dead%40FadeMind) ==> add.Risk :x:

Have a nice day/night.

Cheers,

**Comment by funilrys** [comment]
Hello @FadeMind ,

Just released the results for the following.

[hosts.extras--add.Spam@FadeMind](https://github.com/funilrys/dead-hosts/tree/master/hosts.extras--add.Spam%40FadeMind) ==> add.Spam :x:

Have a nice day/night.

Cheers,

**Comment by funilrys** [comment]
Hello @FadeMind ,

You can find here the result of my last execution of [Funceble](https://github.com/funilrys/funceble) against the following lists.

# add.Spam
- Tested file: https://github.com/FadeMind/hosts.extras/blob/master/add.Spam/hosts

[add.Spam](https://github.com/funilrys/dead-hosts/tree/master/add.Spam)  ==> :x:

```
Status      Percentage   Numbers     
----------- ------------ -------------
ACTIVE      58%          152         
INACTIVE    41%          110         
INVALID     0%           0           
```

# add.Risk
- Tested file: https://github.com/FadeMind/hosts.extras/blob/master/add.Risk/hosts

[add.Risk](https://github.com/funilrys/dead-hosts/tree/master/add.Risk)  ==> :x:

```
Status      Percentage   Numbers     
----------- ------------ -------------
ACTIVE      97%          3063        
INACTIVE    2%           94          
INVALID     0%           0           
```

# add.Dead
- Tested file: https://github.com/FadeMind/hosts.extras/blob/master/add.Dead/hosts

[add.Dead](https://github.com/funilrys/dead-hosts/tree/master/add.Dead)  ==> :x:

```
Status      Percentage   Numbers     
----------- ------------ -------------
ACTIVE      26%          31          
INACTIVE    73%          85          
INVALID     0%           0               
```

# add.2o7Net
- Tested file: https://github.com/FadeMind/hosts.extras/blob/master/add.2o7Net/hosts

[add.2o7Net](https://github.com/funilrys/dead-hosts/tree/master/add.2o7Net)  ==> :white_check_mark: :

```
Status      Percentage   Numbers     
----------- ------------ -------------
ACTIVE      100%         1108        
INACTIVE    0%           0           
INVALID     0%           0            
```

# SpotifyAds
- Tested file: https://github.com/FadeMind/hosts.extras/blob/master/SpotifyAds/hosts

[SpotifyAds](https://github.com/funilrys/dead-hosts/tree/master/SpotifyAds)  ==> :white_check_mark: 

```
Status      Percentage   Numbers     
----------- ------------ -------------
ACTIVE      100%         5           
INACTIVE    0%           0           
INVALID     0%           0           
```

# UncheckyAds
- Tested file: https://github.com/FadeMind/hosts.extras/blob/master/UncheckyAds/hosts

[UncheckyAds](https://github.com/funilrys/dead-hosts/tree/master/UncheckyAds)  ==> :x: 

```
Status      Percentage   Numbers     
----------- ------------ -------------
ACTIVE      50%          17          
INACTIVE    50%          17          
INVALID     0%           0           
```

Have a nice day/night.

Cheers,

## What is funceble?
To quote the most active user of [Funceble](https://github.com/funilrys/funceble):

> [Funceble is an] Excellent script for checking ACTIVE, INACTIVE and EXPIRED Domain Names.

**Comment by FadeMind** [comment]
@funilrys  thank you.

**Comment by funilrys** [comment]
@FadeMind Your welcome. 

Cleanup made, closing
