### ISSUE TITLE
False Positive 'bugs.mysql.com' in 'rlwpx.free.fr.htrc'

### ISSUE THREAD

**Issue by lightswitch05** [FadeMind/hosts.extras#30]
Hello, it looks like `bugs.mysql.com` is being blocked by the `rlwpx.free.fr.htrc` list. This is almost certainly a false positive, right? Or perhaps there is something else going on here? Thank you for your time and help!

**Comment by FadeMind** [comment]
I made mirror long time ago. Please report issue DIRECTLY to http://rlwpx.free.fr/WPFF/mel.htm. If some sites are NEEDED for properly working use whitelists instead.

**Comment by lightswitch05** [comment]
Thanks for the link, I reported here initially because the `issues` link for that repo is here: https://github.com/FadeMind/hosts.extras/blob/master/rlwpx.free.fr.htrc/update.json#L6
