### ISSUE TITLE
[Add] pf4y2a54hx.com

### ISSUE THREAD

**Issue by beerisgood** [FadeMind/hosts.extras#32]
"pf4y2a54hx.com" is a unwanted domain on some streaming sites which popup by itself.

We should block it

**Comment by FadeMind** [comment]
@StevenBlack could you add this to Your custom list? :> Thanks 
@beerisgood  please in future create issue at StevenBlack/hosts repo directly.  hosts.extras repo stored externals resources for this project. Thanks for your feedback.

**Comment by StevenBlack** [comment]
Done Tomasz @FadeMind.

Closing.

**Comment by beerisgood** [comment]
Thanks
