### ISSUE TITLE
pornhubpremium.com

### ISSUE THREAD

**Issue by p1r473** [FadeMind/hosts.extras#34]
Hello,
This is not an ad server, so this domain is acting more as censorship.
This domain is in the following lists: 
hpHosts-MMT/hosts
/hpHosts/hosts

**Comment by FadeMind** [comment]
This is EXTERNAL sources. See JSON  `"url": "https://hosts-file.net/mmt.txt"`. Wontfix, cause will be overwritten after update from this URL.
