### ISSUE TITLE
hosts-file.net decomissioned

### ISSUE THREAD

**Issue by p1r473** [FadeMind/hosts.extras#35]
Hi @FadeMind 
A few I had to make a new issue as I could not comment on #34 anymore. I get issue "Repository owner locked and limited conversation to collaborators yesterday"

hosts-file.net has been decomissioned, so there will be no overwriting after update from this URL. So, you can safely remove pornhubpremium.com without fear of overwriting, as it is a false positive

**Comment by FadeMind** [comment]
https://github.com/FadeMind/hosts.extras/commit/459408a4a64002a016276aa273ba91495f4d182e
