### ISSUE TITLE
Blocking spclient.wg.spotify.com breaks Spotify Premium

### ISSUE THREAD

**Issue by ThePowerOfDreams** [FadeMind/hosts.extras#39]
Blocking spclient.wg.spotify.com breaks logging into Spotify's macOS app (even with a Spotify Premium account). I filed a [PR](https://github.com/FadeMind/hosts.extras/pull/38) a couple of weeks ago to remove it from your blocklist, as it's pulled in as part of NextDNS's Streaming Ads list; could you approve it?

**Comment by FadeMind** [comment]
Next time **please** do research
https://github.com/FadeMind/hosts.extras/issues/13#issuecomment-378483477
https://github.com/FadeMind/hosts.extras/issues/25

See: https://github.com/abba23/spotify-adblock-linux/blob/master/blacklist.h

**Comment by ThePowerOfDreams** [comment]
Did you stop to think that maybe things have changed on Spotify's end in the two years since then?

**Comment by FadeMind** [comment]
What is problem with WHITELIST for user self? 
I collect only domains with ads/tracking for streaming. Not review them against compatibility during time. 

Lots of domains should be whitelisted against incompatibility (video streaming blocking cause cannot loading some JS)

Thats why hosts blocking ads can be problematic and whitelisting SHOULD BE done via user self. 
See sample https://github.com/FadeMind/00-HSTS.EXT/blob/master/whitelist

**Comment by llacb47** [comment]
You are wrong, `spclient.wg.spotify.com` is an essential endpoint - otherwise songs/playlists/albums will not load.

**Comment by FadeMind** [comment]
aaand end point for ADS.

**Comment by llacb47** [comment]
Yes, spotify ads cannot be blocked by any hosts file. Basically your list is a futile experiment.

**Comment by ThePowerOfDreams** [comment]
Ads are irrelevant if the whole site is broken. This is packaged as a hosts file! If you block that host, all of Spotify is blocked. Thus, the list is broken.

**Comment by ThePowerOfDreams** [comment]
> Yes, spotify ads cannot be blocked by any hosts file without breaking normal playback/functionality. Basically your list is a futile endeavor.

Only futile for Spotify AFAIK (well, for now, at least).

**Comment by FadeMind** [comment]
@ThePowerOfDreams you know VALID hosts working with spotify? Or it is imposible so - I should purge them aand issue will gone?

**Comment by ThePowerOfDreams** [comment]
> @ThePowerOfDreams @llacb47 done
> 
> [19462d9](https://github.com/FadeMind/hosts.extras/commit/19462d9b5eefb991967aac5c1c0e7da4e4428a90)

🤯

Talk about biting off your nose to spite your face.
