### ISSUE TITLE
www.tiptanks.com

### ISSUE THREAD

**Issue by p1r473** [FadeMind/hosts.extras#40]
This comes from the decomissioned rlwpx.free.fr.htrc I guess.
This is a stock tips investing website. They give price targets on stocks. It is not malicious not advertising.

**Comment by FadeMind** [comment]
@p1r473  site is dead

**Comment by p1r473** [comment]
Sorry, there was a typo. It is supposed to say www.tipranks.com.

**Comment by FadeMind** [comment]
@p1r473 done. Regards

**Comment by p1r473** [comment]
Thanks 👍
