### ISSUE TITLE
Tracking domain to add: assets.customer.io

### ISSUE THREAD

**Issue by Ghalid** [FadeMind/hosts.extras#41]
I noticed requests to `assets.customer.io` when going to https://www.smore.com/. Monitoring network requests in the browser shows that the site's home page is attempting to get a resource `https://assets.customer.io/assets/track.js`, which seems to be quite clearly a tracking script. You should be able to reproduce this by simply clicking the link above and observing network requests in your browser.

I did not see any functionality break as a result of blocking this domain, but I also have not personally seen this domain elsewhere.

**Comment by FadeMind** [comment]
@StevenBlack  please see.

@Ghalid in future please open report directly here: https://github.com/StevenBlack/hosts/issues
