### ISSUE TITLE
malwaredomains to add https://mirror.cedia.org.ec/malwaredomains/justdomains

### ISSUE THREAD

**Issue by tscpd** [FadeMind/hosts.extras#44]
hi, malwaredomains to add https://mirror.cedia.org.ec/malwaredomains/justdomains

**Comment by tscpd** [comment]
Would you mind to elaborate real quick? Has this list already been considered in the past? Or why is it disqualified? Thanks.

**Comment by FadeMind** [comment]
@tscpd I though it is duplicate of `sint.digitalside.it` my bad. Anyway. I did not see any license note and it is not in hosts format.

**Comment by FadeMind** [comment]
@StevenBlack  maybe you should backport it officialy these? :thinking:

**Comment by StevenBlack** [comment]
Hi Tomasz @FadeMind, 

* I'm not seeing any curation history.
* No file header.
* 26,854 domains
* Intersection with our main list: 42.  That's just, statistically implausible.

I respectfully decline.  But I'm open to better evidence, and alternate interpretations.

**Comment by spirillen** [comment]
![image](https://user-images.githubusercontent.com/44526987/96525673-e65c0600-127b-11eb-85ab-6fce4b99d03f.png)

![image](https://user-images.githubusercontent.com/44526987/96525708-faa00300-127b-11eb-962e-a118843b38c9.png)

**Comment by FadeMind** [comment]
@StevenBlack @tscpd and now is more clarify

https://github.com/gorhill/uBlock/commit/a13ac920892d25ba0bf431ea1410fd3c8612b2d6#diff-867c526785ad7b2296cb4d7ad5a069232add7ad772faf27beba1ce9570f288ab

**Comment by StevenBlack** [comment]
I'm struggling to understand what you mean Tomasz @FadeMind.  What am I looking for, here?  I read all the comments in that commit, and nothing strikes me as relevant to this thread.  Help me?

**Comment by FadeMind** [comment]
- `justdomains` was abaddoned.  urlhaus is used instead in this place. 
- malware domains /  justdomains is now dead project hosted in several mirrors (cedia.org.ec is one of them).

**Comment by tscpd** [comment]
yes, i got this feedback also from a other side: its deprecated, thanks anyways
