### ISSUE TITLE
Threat domains from osint.digitalside.it

### ISSUE THREAD

**Issue by tscpd** [FadeMind/hosts.extras#45]
hi, threatdomains to add https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt

**Comment by FadeMind** [comment]
I don't see hosts format here, only generic domains list. Please prepare or consult with @davidonzo creating directly hosts file format with malware domains. 

Related https://github.com/davidonzo/Threat-Intel/

Info for @StevenBlack  too.

**Comment by davidonzo** [comment]
Is it good for you this way?
- https://github.com/davidonzo/Threat-Intel/blob/master/lists/latestdomains.piHole.txt
- https://osint.digitalside.it/Threat-Intel/lists/latestdomains.piHole.txt

**Comment by FadeMind** [comment]
@davidonzo thank you. I will merged this soon.

**Comment by FadeMind** [comment]
@StevenBlack please include it officialy in your project if you like. 
@davidonzo  @tscpd merged.

**Comment by tscpd** [comment]
great, thanks! @davidonzo please keep this host-format file up-to-date so it can go in @StevenBlack list and stay there to in keep many people more secure. thank you very much

**Comment by davidonzo** [comment]
@tscpd the new list file will be updated as the whole repository.
No problem for this.

Glad to be useful.
