### ISSUE TITLE
Why is Unchecky missing so many entries?

### ISSUE THREAD

**Issue by Flipmode11** [FadeMind/hosts.extras#46]
I can see only 10 rows in the Unchecky hosts.
**
Seems to be missing everything else from when I downloaded in 2017:
`# >> UnChecky Windows installer Adverts 2017.07.20 #<?`
`# https://github.com/FadeMind/hosts.extras/tree/master/UncheckyAds # https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts`
`0.0.0.0 cdn.appround.biz cdn.bigspeedpro.com cdn.bispd.com cdn.bisrv.com inno.bisrv.com nsis.bisrv.com cdn.download.sweetpacks.com cdn.guttastatdk.us cdn.inskinmedia.com`
`0.0.0.0 cdn.insta.playbryte.com cdn.msdwnld.com cdn.mypcbackup.com cdn.riceateastcach.us d3oxtn1x3b8d7i.cloudfront.net installer.betterinstaller.com installer.filebulldog.com tracking.opencandy.com.s3.amazonaws.com`
`0.0.0.0 api.recommendedsw.com cdn.goateastcach.us cdn.insta.oibundles2.com cdn.llogetfastcach.us cdn.shyapotato.us cdn.solimba.com cdn.tuto4pc.com cdn.cdndp.com cdn.dpdownload.com cdn.visualbee.net`

Current UnChecky Hosts:
`0.0.0.0 cdn.appround.biz cdn.download.sweetpacks.com cdn.insta.playbryte.com cdn.msdwnld.com cdn.mypcbackup.com`
`0.0.0.0 inno.bisrv.com nsis.bisrv.com installer.betterinstaller.com installer.filebulldog.com tracking.opencandy.com.s3.amazonaws.com`

Have the hosts from 2017 been removed due to those servers no longer being a threat?
**Thanks! :D**

**Comment by FadeMind** [comment]
Duplicate https://github.com/FadeMind/hosts.extras/issues/43
