### ISSUE TITLE
economictimes.indiatimes.com

### ISSUE THREAD

**Issue by p1r473** [FadeMind/hosts.extras#47]
Hi,
This news site is being blocked and I feel it is a false positive
It is an economic paper from an Indian news source
Not advertising/adware/spyware/malware

Thanks

**Comment by FadeMind** [comment]
Hi, @p1r473  where exactly is stored?

**Comment by p1r473** [comment]
@FadeMind 

https://raw.githubusercontent.com/FadeMind/hosts.extras/master/rlwpx.free.fr.htrc/hosts 

Thanks

**Comment by FadeMind** [comment]
@p1r473 done. Thanks for contribution.
