### ISSUE TITLE
Is whitelisting of s0.2mdn.net still the case?

### ISSUE THREAD

**Issue by crssi** [FadeMind/hosts.extras#49]
`s0.2mdn.net` seem pretty prevalent and blocking it I haven't found single site to break.
I would tried `mtv.ca` and `cbs.com` to recheck that whitelisting `s0.2mdn.net` is still needed, but those are geo-fenced and doesn't play in my region unfortunately.

Would you reconsider to remove `s0.2mdn.net` from whitelist https://github.com/FadeMind/hosts.extras/blob/master/whitelist ?

Thank you and cheers

**Comment by FadeMind** [comment]
@StevenBlack @crssi 
Hi
Still whitelisting in oisd. 
https://oisd.nl/excludes.php?w=2mdn.net

**Comment by crssi** [comment]
Sure it is, and the first reason ir your list 😉 
See `https://oisd.nl/excludes.php?w=s0.2mdn.net`

**Comment by crssi** [comment]
Chasing the tail. 😉 
Any verdict?

Thank you and cheers

**Comment by FadeMind** [comment]
@crssi whiltelist file only suggest. I will not delete from file `2mdn.net` until will be not removed mainstream from other whitelist. 
Cheers

**Comment by crssi** [comment]
I guess that with `from other whitelist` you do not mean OISD?
Because OISD has listed it from your list. 😄 

Cheers

**Comment by FadeMind** [comment]
https://raw.githubusercontent.com/notracking/hosts-blocklists-scripts/master/hostnames.whitelist.txt

```
# https://github.com/StevenBlack/hosts/issues/419
 s0.2mdn.net
 2mdn.net
```

**Comment by crssi** [comment]
And there we go all around: https://github.com/StevenBlack/hosts/issues/1560

**Comment by FadeMind** [comment]
Just wait for feedback UPSTREAM.  Closing.
