### ISSUE TITLE
Domain secure.vxsbill.com

### ISSUE THREAD

**Issue by StevenBlack** [FadeMind/hosts.extras#5]
Hi @FadeMind, I just received an inquiry: why is [`secure.vxsbill.com`](https://github.com/FadeMind/hosts.extras/blob/ca35701d82df4b8fdc52beac9c5ee385d99b17a2/add.Risk/hosts#L1415) listed?

Thanks!

**Comment by FadeMind** [comment]
`add.*` sources are taken from http://hostsfile.org/hosts.html. If you want I can just removing this domain from file if needed.

**Comment by StevenBlack** [comment]
Ah, hostfile.org :-) 

Yes, please remove it.  Thanks Tomasz!
