### ISSUE TITLE
pastie.org in add.Risk

### ISSUE THREAD

**Issue by The-Compiler** [FadeMind/hosts.extras#54]
[Pastie](http://pastie.org/) seems to be a generic pastebin website, but is [blocked](https://github.com/FadeMind/hosts.extras/blob/2a9cefed36e5b2bbd83cb54b7d7397d3394cdbac/add.Risk/hosts#L817) in `add.Risk` - it probably shouldn't be?

**Comment by FadeMind** [comment]
@The-Compiler thanks for report. Resolved.  Note: I only mirrored http://hostsfile.org/hosts.html and customized against false-positives like this. 
Regards
