### ISSUE TITLE
nulledwp.click: blacklist

### ISSUE THREAD

**Issue by 3xploiton3** [FadeMind/hosts.extras#60]
https://nulledwp.click/wordpress/WordPress

contain redirect to survey site

**Comment by FadeMind** [comment]
@StevenBlack could you handle it?

**Comment by StevenBlack** [comment]
@FadeMind what is the problem here? I don't understand.

**Comment by FadeMind** [comment]
@StevenBlack `nulledwp.click` is blocked or should be blocked? OP does not specify this. @3xploiton3

**Comment by 3xploiton3** [comment]
should be blocked

**Comment by FadeMind** [comment]
@3xploiton3 open issue here https://github.com/StevenBlack/hosts closing.
