### ISSUE TITLE
Block OneTrust Privacy Annoyances

### ISSUE THREAD

**Issue by riei2922jww** [FadeMind/hosts.extras#63]
Please add:
my.onetrust.com
geolocation.onetrust.com
mobile-data.onetrust.io

To the blocklist to prevent these annoying cookie pop-ups on 70% of mobile-based applications.
![image](https://github.com/FadeMind/hosts.extras/assets/154846714/f1a3c108-824c-4d60-93c8-aec4ee1e498b)

**Comment by smed79** [comment]
@riei2922jww Can cause false positive.
See https://github.com/easylist/easylist/issues/15831

**Comment by FadeMind** [comment]
@smed79  this repo is not intendent to add new entries. @riei2922jww
