### ISSUE TITLE
License is misleading, does not speak for contained host files

### ISSUE THREAD

**Issue by brarcher** [FadeMind/hosts.extras#9]
It is not obvious what the [License](https://github.com/FadeMind/hosts.extras/blob/master/LICENSE) applies to in this project. My goal is to document the licenses which apply for various host files for the StevenBlack/hosts project. In doing so, I found that the LICENSE file in this project says MIT, but the host files from hostsfile.org are actually licensed under LGPLv3 (no version is specified, which mean it is the latest).

I'll be updating the documentation on StevenBlack/hosts to reflect this. Just wanted you to be aware of the confusion, in case you want to add additional documentation around the host files in this project and the applicable licenses.

**Comment by FadeMind** [comment]
I followed @StevenBlack hosts project license type. Please create pull request with needed changes. Thanks.

**Comment by FadeMind** [comment]
@brarcher merged. Thanks. Feel free pull new ideas/fixes. Thanks.

RESOLVED in https://github.com/FadeMind/hosts.extras/commit/8fcc5dbc372a542ca956c51eb7b74206904a2472
